/**
 * Entry-contract gate: verifies that `src/index.ts` still exports the public
 * API surface this package documents and depends on.
 *
 * The extension entry (`extensions/workflow.ts`), the README's library API,
 * and the test suites all import from `src/index.js`. A rename or accidental
 * removal of any of those names would only surface at runtime inside a pi
 * session — this script turns that into a fast, deterministic CI failure by
 * resolving the module's ACTUAL exports with the TypeScript checker and
 * diffing them against the frozen contract below.
 *
 * Contract policy:
 *  - Every name in ENTRY_CONTRACT must be exported (missing → exit 1).
 *  - Exports NOT in the contract are reported as warnings (exit 0): the
 *    contract should grow with the public API, so keep it current when you
 *    add an export — but a new export must never silently break the gate.
 *
 * Run: `npm run check:entry-contract` (wired into `npm run check` → CI).
 */
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import ts from "typescript";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const ENTRY_FILE = join(REPO_ROOT, "src", "index.ts");

/**
 * Frozen public entry contract, keyed by export name with the reason the name
 * is contractual. Curated from: the extension entry's imports
 * (extensions/workflow.ts), README-documented library API, and the test suites
 * that import from src/index.js.
 */
const ENTRY_CONTRACT: Record<string, string> = {
  // ── extension entry (extensions/workflow.ts) — every import must resolve ──
  createEffortState: "extension entry imports it",
  createGatewayProxiedTools: "extension entry imports it",
  createWebTools: "extension entry imports it",
  createWorkflowControlTool: "extension entry imports it",
  createWorkflowStorage: "extension entry imports it",
  createWorkflowTool: "extension entry imports it",
  HostToolGateway: "extension entry imports it",
  hostToolsFromDefinitions: "library API (HostToolGateway family; tests import it)",
  installResultDelivery: "extension entry imports it",
  installTaskPanel: "extension entry imports it",
  installWorkflowKeywordArming: "extension entry imports it",
  loadWorkflowSettings: "extension entry imports it",
  registerAllSavedWorkflows: "extension entry imports it",
  registerBuiltinWorkflows: "extension entry imports it",
  registerEffortCommand: "extension entry imports it",
  registerWorkflowCommands: "extension entry imports it",
  registerWorkflowGatewayCommand: "extension entry imports it",
  registerWorkflowModelsCommand: "extension entry imports it",
  registerWorkflowSettingsCommand: "extension entry imports it",
  registerWorkflowSubagentToolsCommand: "extension entry imports it",
  buildSubagentToolRows: "subagent-tools listing command (renderer, tests import it)",
  classifyToolSource: "subagent-tools listing command (renderer, tests import it)",
  renderSubagentToolsListing: "subagent-tools listing command (renderer, tests import it)",
  SubagentToolRow: "subagent-tools listing command (type)",
  SubagentToolSource: "subagent-tools listing command (type)",
  SubagentToolStatus: "subagent-tools listing command (type)",
  SubagentToolsListingInput: "subagent-tools listing command (type)",
  SubagentToolsMode: "subagent-tools listing command (type)",
  WorkflowSubagentToolsCommandOptions: "subagent-tools listing command (type)",
  saveWorkflowSettingsForCwd: "extension entry imports it",
  UsageLimitScheduler: "extension entry imports it",
  WorkflowManager: "extension entry imports it",
  // ── README-documented library API / headless override layer ──
  applyEnvSettingsOverride: "config env override layer (entry-config:i2)",
  FAN_OUT_APPROVAL_THRESHOLD_DEFAULT: "P12 fan-out approval gate default (config + settings UI share it)",
  MAX_RECURSIVE_DEPTH: "V2-P07 recursive() hard depth ceiling (config + runtime share it)",
  DEFAULT_RECURSIVE_DEPTH: "V2-P07 recursive() default per-branch depth (config + runtime share it)",
  DEFAULT_RECURSIVE_MAX_ROOTS: "V2-P07 recursive() default per-level wave width (config + runtime share it)",
  DEFAULT_REPLAN_THRESHOLD: "V2-P11 re-plan forecast threshold default (config + runtime share it)",
  DEFAULT_SUBAGENT_EXTENSION_TOOLS:
    "P04 default knob for subagentExtensionTools (extension entry + settings UI share it)",
  workflowSettingsFromEnv: "config env override layer (entry-config:i2)",
  WORKFLOW_ENV_PREFIX: "config env override layer (entry-config:i2)",
  WORKFLOW_ENV_VARS: "config env override layer (entry-config:i2)",
  runWorkflow: "README + runtime test suites",
  parseWorkflowScript: "public script parsing API",
  buildReplayFixture: "V2-P10 replay harness (fixture generation from a recorded journal)",
  buildReplayFixtureFromRun: "V2-P10 replay harness (fixture generation from a persisted run)",
  createReplayAgent: "V2-P10 replay harness (no-launch mock agent executor)",
  createReplayResumeJournal: "V2-P10 replay harness (resume-map construction)",
  isReplayMiss: "V2-P10 replay harness (REPLAY_MISS type guard)",
  parseReplayFixture: "V2-P10 replay harness (inline fixture validation)",
  REPLAY_FIXTURE_SCHEMA_VERSION: "V2-P10 replay harness (fixture schema version)",
  replayFixtureToJournalEntries: "V2-P10 replay harness (fixture → journal inverse)",
  replaySignature: "V2-P10 replay harness (golden-master signature)",
  replayWorkflow: "V2-P10 replay harness (replay a script against a fixture)",
  replayWorkflowFromJournal: "V2-P10 replay harness (replay a script against a raw journal)",
  stringifyReplaySignature: "V2-P10 replay harness (golden-master canonical JSON)",
  readRunJournalForReplay: "V2-P10 replay harness (persisted-run journal read)",
  RunJournalForReplay: "V2-P10 replay harness (persisted-run journal source type)",
  ReplayAgentOptions: "V2-P10 replay harness (replay-agent options type)",
  ReplayFixture: "V2-P10 replay harness (canned fixture type)",
  ReplayFixtureEntry: "V2-P10 replay harness (per-call fixture entry type)",
  ReplayFixtureSource: "V2-P10 replay harness (fixture source type)",
  ReplayMiss: "V2-P10 replay harness (miss record type)",
  ReplaySignature: "V2-P10 replay harness (golden-master signature type)",
  // ── P05 per-agent result cap (runtime pure functions, tests import them) ──
  capAgentResultText: "P05 per-agent result cap (pure truncation helper)",
  resolveMaxAgentResultChars: "P05 per-agent result cap (cap resolution)",
  truncateAgentResultMiddle: "P05 per-agent result cap (middle truncation)",
  countOutputChars: "V2-QW3 run-level output accumulator (deterministic result char count)",
  CappedAgentResult: "P05 per-agent result cap (result type)",
  DEFAULT_MAX_AGENT_RESULT_CHARS: "P05 per-agent result cap default (config constant)",
  estimateTokens: "P05 per-agent result cap + N04 report (T1-16 segment-aware token estimator)",
  // ── V2-N4 pre-flight estimate (workflow --estimate, pure engine + renderer) ──
  estimateWorkflowForecast: "V2-N4 pre-flight cost/duration forecast (pure AST scan)",
  renderWorkflowEstimate: "V2-N4 pre-flight forecast human-line renderer",
  formatEstimateDuration: "V2-N4 pre-flight forecast duration formatter",
  EstimateCallKind: "V2-N4 pre-flight forecast call-kind union (type)",
  EstimateCallRecord: "V2-N4 pre-flight forecast call record (type)",
  EstimateFanOutRow: "V2-N4 pre-flight forecast fan-out row (type)",
  EstimateOptions: "V2-N4 pre-flight forecast options (type)",
  EstimatePhaseRow: "V2-N4 pre-flight forecast phase row (type)",
  WorkflowEstimate: "V2-N4 pre-flight forecast shape (type)",
  ESTIMATE_REPLY_TOKENS_PER_AGENT_DEFAULT: "V2-N4 reply-token forecast assumption (config constant)",
  ESTIMATE_TOKENS_PER_SECOND_DEFAULT: "V2-N4 duration-model throughput (config constant)",
  ESTIMATE_AGENT_OVERHEAD_MS_DEFAULT: "V2-N4 duration-model overhead (config constant)",
  ESTIMATE_WARNING_BUDGET_FRACTION: "V2-N4 budget-proximity warn threshold (config constant)",
  ESTIMATE_TIER_COST_WEIGHTS: "V2-N4 relative per-tier cost weights (config constant)",
  // ── N01 workspace change-scope fingerprint (host-side fs/git + machine diff) ──
  captureWorkspaceFingerprint: "N01 workspace fingerprint capture (host-side git)",
  diffWorkspaceFingerprints: "N01 workspace fingerprint machine diff",
  parseGitStatusLine: "N01 workspace fingerprint porcelain parsing",
  workspaceScopeViolations: "N01 workspace fingerprint scope assertion",
  WorkspaceScopeDiff: "N01 workspace fingerprint diff type",
  WorkspaceFingerprint: "N01 workspace fingerprint shape (phase state sidecar)",
  // ── P06 durable store + provenance ledger (cross-run KV, tests import them) ──
  DURABLE_STORE_SCHEMA_VERSION: "P06 durable store on-disk schema version",
  DurableStore: "P06 durable store class (cross-run KV)",
  ProvenanceEntry: "P06 provenance ledger entry type",
  bindRunDurableStore: "P06 per-run store binding (runtime injection)",
  closeRunDurableStore: "P06 store lifecycle (release run registry)",
  createRunDurableStore: "P06 store factory (project-scoped, schema-versioned)",
  deterministicRunClock: "P06 deterministic provenance timestamps (replay-stable)",
  provenanceContentId: "V2-N5 content-derived provenance id (FNV-1a, replay-stable machine-gate ids)",
  ProvenanceSourceKind: "V2-N5 provenance ledger source-kind union (machine-gate kinds)",
  recordProvenance: "P06 host-side provenance ledger writer",
  runDurableStore: "P06 run registry lookup (host emission points)",
  // ── V2-P03 edit transaction (snapshot + gated commit + rollback + auto test-scope) ──
  createEditTransaction: "V2-P03 edit-transaction factory (begin/commit/rollback/scopeDiff)",
  DEFAULT_TEST_SCOPE_COMMAND: "V2-P03 default testScope-to-command derivation (node:test + tsx loader)",
  deriveTestGateTestsFromPartition: "V2-P03 auto test-scope: impact partition → testGate tests",
  deriveTestGateTestsFromScope: "V2-P03 auto test-scope: testScope file list → testGate tests",
  EDIT_TRANSACTION_FINGERPRINT_PHASE: "V2-P03 snapshot fingerprint phase label constant",
  EDIT_TRANSACTION_MAX_SNAPSHOT_FILES: "V2-P03 snapshot file-count cap constant",
  EDIT_TRANSACTION_MAX_SNAPSHOT_FILE_BYTES: "V2-P03 snapshot per-file byte cap constant",
  EDIT_TRANSACTION_SUBDIR: "V2-P03 snapshot subdir constant (getAgentDir()/edit-transactions)",
  pruneEditTransactionSnapshots: "V2-P03 run-sweep snapshot cleanup (runId-namespaced)",
  resolveRepoRoot: "V2-P03 repo-root resolver (rollback git-restore anchor)",
  testScopeFromPartition: "V2-P03 partition testScope flattener (dedup, deterministic)",
  EditTransaction: "V2-P03 transaction surface type (edit-transaction.ts, type)",
  EditTransactionBeginResult: "V2-P03 begin() result type (edit-transaction.ts, type)",
  EditTransactionCommitOptions: "V2-P03 commit() options type (edit-transaction.ts, type)",
  EditTransactionCommitResult: "V2-P03 commit() result type (edit-transaction.ts, type)",
  EditTransactionOptions: "V2-P03 factory options type (edit-transaction.ts, type)",
  EditTransactionRollbackResult: "V2-P03 rollback() result type (edit-transaction.ts, type)",
  EditTransactionSnapshot: "V2-P03 snapshot manifest type (edit-transaction.ts, type)",
  EditTransactionState: "V2-P03 lifecycle state union (edit-transaction.ts, type)",
  EditTransactionFs: "V2-P03 fs-layer surface type (edit-transaction.ts, type)",
  // ── V2-P12 session-scoped host-event actors (cross-run watchdog/advisor/spec) ──
  createHostActorManager: "V2-P12 session-scoped actor manager factory (host-actors.ts)",
  HostActorManager: "V2-P12 actor manager class (host-actors.ts)",
  HostActorsConfigError: "V2-P12 invalid actor config error (host-actors.ts)",
  HOST_ACTOR_EVENT_TYPES: "V2-P12 host event type union constant (host-actors.ts)",
  HOST_ACTOR_MESSAGE_CUSTOM_TYPE: "V2-P12 delivered custom-message customType tag (host-actors.ts)",
  HOST_ACTORS_CONTEXT_VIEW_MAX_CHARS: "V2-P12 context observation view cap constant (host-actors.ts)",
  HOST_ACTORS_ACTIVATION_CAP_DEFAULT: "V2-P12 per-actor activation budget default (config.ts)",
  HOST_ACTORS_QUEUE_MAX: "V2-P12 per-actor serial-mailbox journal cap (config.ts)",
  HOST_ACTORS_WATCHDOG_DRIFT_THRESHOLD_DEFAULT: "V2-P12 watchdog drift threshold default (config.ts)",
  assertValidActorConfig: "V2-P12 actor config validator (host-actors.ts)",
  parseHostActorConfigs: "V2-P12 lenient actors.json def parser (host-actors.ts)",
  normalizeDeliveryPolicy: "V2-P12 delivery-policy normalizer (triggerTurn supervisor-only gate)",
  defaultDeliveryForProfile: "V2-P12 per-profile default delivery policy (host-actors.ts)",
  defaultSubscriptionsForProfile: "V2-P12 per-profile default subscription set (host-actors.ts)",
  goalSimilarity: "V2-P12 watchdog drift heuristic (pure Jaccard token similarity)",
  tokenSet: "V2-P12 token-set core for goalSimilarity (host-actors.ts)",
  fnv1aHex: "V2-P12 deterministic FNV-1a content hash (spec criterion ids)",
  extractAcceptanceCriteria: "V2-P12 spec criterion extraction (host-actors.ts)",
  normalizeCriterionText: "V2-P12 criterion text normalization (host-actors.ts)",
  isAcceptanceCriterionLine: "V2-P12 criterion-line predicate (host-actors.ts)",
  promptCarriesDoneMarker: "V2-P12 spec verified-transition marker predicate (host-actors.ts)",
  criterionMentioned: "V2-P12 criterion-mention predicate (host-actors.ts)",
  triggerMatches: "V2-P12 advisor/supervisor trigger matcher (host-actors.ts)",
  boundedContextView: "V2-P12 defensive bounded context projection (host-actors.ts)",
  SPEC_ACCEPTANCE_MARKERS_DEFAULT: "V2-P12 spec default acceptance markers (host-actors.ts)",
  SPEC_DONE_MARKERS_DEFAULT: "V2-P12 spec default done markers (host-actors.ts)",
  SPEC_SUBSCRIPTIONS_DEFAULT: "V2-P12 spec default subscriptions (host-actors.ts)",
  WATCHDOG_SUBSCRIPTIONS_DEFAULT: "V2-P12 watchdog default subscriptions (host-actors.ts)",
  ActorContribution: "V2-P12 actor contribution type (host-actors.ts, type)",
  ActorDeliveryMode: "V2-P12 delivery mode union type (host-actors.ts, type)",
  ActorDeliveryPolicy: "V2-P12 delivery policy type (host-actors.ts, type)",
  AdvisorActorConfig: "V2-P12 advisor config type (host-actors.ts, type)",
  BeforeAgentStartActorPayload: "V2-P12 before_agent_start payload type (host-actors.ts, type)",
  ContextActorPayload: "V2-P12 context payload type (host-actors.ts, type)",
  HostActorConfig: "V2-P12 actor config union type (host-actors.ts, type)",
  HostActorConfigBase: "V2-P12 shared actor config type (host-actors.ts, type)",
  HostActorEventRecord: "V2-P12 serial-mailbox journal entry type (host-actors.ts, type)",
  HostActorEventType: "V2-P12 host event type union (host-actors.ts, type)",
  HostActorManagerOptions: "V2-P12 manager options type (host-actors.ts, type)",
  HostActorMessage: "V2-P12 delivered custom-message type (host-actors.ts, type)",
  HostActorPayload: "V2-P12 normalized event payload union (host-actors.ts, type)",
  HostActorProfile: "V2-P12 actor profile union (host-actors.ts, type)",
  HostActorState: "V2-P12 persisted per-actor state type (host-actors.ts, type)",
  HostActorSummary: "V2-P12 actor summary type (host-actors.ts, type)",
  SessionCompactActorPayload: "V2-P12 session_compact payload type (host-actors.ts, type)",
  SessionStartActorPayload: "V2-P12 session_start payload type (host-actors.ts, type)",
  SpecActorConfig: "V2-P12 spec config type (host-actors.ts, type)",
  SpecCriterion: "V2-P12 spec ledger criterion type (host-actors.ts, type)",
  SupervisorActorConfig: "V2-P12 supervisor config type (host-actors.ts, type)",
  WatchdogActorConfig: "V2-P12 watchdog config type (host-actors.ts, type)",
  // ── V2-N1 machine completion criteria for supervisedRun ──
  MachineCriterionFunction: "V2-N1 script-side criterion predicate type (supervisor.ts, type)",
  MachineCriterionSpec: "V2-N1 testGate-style criterion spec type (supervisor.ts, type)",
  MachineCriterionVerdict: "V2-N1 machine criterion verdict type (supervisor.ts, type)",
  SupervisedRunCriterion: "V2-N1 widened criterion union type (supervisor.ts, type)",
  SupervisedRunCriterionMode: "V2-N1 criterion evaluation mode union (supervisor.ts, type)",
  buildTaskPrompt: "V2-N1 task-agent prompt builder (supervisor.ts; criterion union renderer)",
  describeCriterion: "V2-N1 deterministic criterion renderer (supervisor.ts)",
  normalizeMachineFunctionVerdict: "V2-N1 machine predicate verdict normalizer (supervisor.ts)",
  resolveSupervisedRunCriterion: "V2-N1 criterion mode resolver + validator (supervisor.ts)",
  // ── N04/QW3/QW5 machine-readable run report (derived, additive artifact) ──
  RUN_REPORT_SCHEMA_VERSION: "N04 run report schema version",
  RunReport: "N04 run report type",
  RunReportAgent: "N04 run report per-agent roster type",
  RunReportPhase: "N04 run report per-phase budget type",
  RunReportOutputBudget: "V2-QW3 run report output-budget block type",
  RunReportSummary: "V2-QW5 recent-reports listing row type",
  buildRunReport: "N04 run report builder (derived from persisted state)",
  deriveTruncationReports: "N04 run report truncation derivation (QW3, from persisted logs)",
  listRunReports: "V2-QW5 recent-reports listing helper (runsDir/reports scan)",
  readRunReport: "V2-QW5 report artifact reader (missing-file safe)",
  terminationReason: "N04 run report termination classification",
  writeRunReport: "N04 run report writer (runsDir/reports/<runId>.json)",
  generateDeepResearchWorkflow: "builtin /deep-research",
  generateCodeReviewWorkflow: "builtin /code-review",
  MAX_DIFF_CHARS: "builtin /code-review",
  diffShard: "builtin /code-review diff sharding",
  CODE_REVIEW_ANGLES: "builtin /code-review diff sharding",
  generateAdversarialReviewWorkflow: "builtin adversarial review",
  generateMultiPerspectiveWorkflow: "builtin multi-perspective",
  generateCodebaseAuditWorkflow: "builtin codebase audit",
  generatePlanThenExecuteWorkflow: "builtin plan-then-execute",
  orderStepsByDependencies: "builtin plan-then-execute step ordering",
  PLAN_THEN_EXECUTE_MAX_PLAN_ATTEMPTS: "builtin plan-then-execute constant",
  PLAN_THEN_EXECUTE_MAX_REWORK_ATTEMPTS: "builtin plan-then-execute constant",
  PLAN_THEN_EXECUTE_NUMERIC_ARGS: "builtin plan-then-execute constant",
  generateSpecGenerationWorkflow: "builtin spec-generation",
  normalizeSpecArtifact: "builtin spec-generation artifact normalization",
  SPEC_GENERATION_DEFAULT_FORMAT: "builtin spec-generation constant",
  SPEC_GENERATION_FORMATS: "builtin spec-generation constant",
  // ── config constants (export * from ./config.js) ──
  MAX_AGENTS_PER_RUN: "config constant",
  DEFAULT_AGENT_TIMEOUT_MS: "config constant",
  DRAIN_ABORT_TIMEOUT_MS: "config constant",
  MAX_CONCURRENCY: "config constant",
  MAX_NESTED_WORKFLOW_DEPTH: "config constant",
  MAX_AGENT_RETRIES: "config constant",
  // T2-03/T2-04/T2-05/T2-11 routing-economics constants (slice C).
  UNTAGGED_TIER_ECONOMY: "config constant (T2-03 economy default sentinel)",
  UNTAGGED_TIER_INHERIT_MAIN: "config constant (T2-03 opt-out sentinel)",
  DEFAULT_UNTAGGED_TIER: "config constant (T2-03 run default)",
  ROUTING_POLICY_VERSION: "config constant (T2-03/05/11 resume-hash policy version)",
  DEFAULT_HELPER_TIER: "config constant (T2-04 quality-helper vote tier)",
  DEFAULT_TEST_GATE_ATTEMPTS: "config constant (W2 P01 testGate bounded-rework default)",
  DEFAULT_TEST_GATE_TOOL: "config constant (W2 P01 testGate default subagent tool)",
  DEFAULT_CROSSCHECK_TIMEOUT_MS: "config constant (W2 P09 cross-check request timeout)",
  DEFAULT_APPROVAL_POLICY: "V2-P01 config constant (default per-risk-class approval policy)",
  DEFAULT_APPROVAL_CLASSIFIER_TIMEOUT_MS: "V2-P01 config constant (approval-classifier request timeout)",
  DEFAULT_APPROVAL_CLASSIFIER_MAX_TOKENS: "V2-P01 config constant (approval-classifier response token cap)",
  APPROVAL_CLASSIFIER_MAX_EVIDENCE_CHARS: "V2-P01 config constant (bounded classifier evidence cap)",
  createModelCrosschecker: "W2 P09 second-model cross-checker factory (model-crosscheck.ts)",
  parseCrosscheckVerdict: "W2 P09 cross-check verdict parser (model-crosscheck.ts)",
  resolveModelForCrosscheck: "W2 P09 model-spec resolver over ModelRuntime (model-crosscheck.ts)",
  ApprovalGrantStore: "V2-P01 per-run approval grant store (approval-policy.ts)",
  approvalGrantKey: "V2-P01 action-exact grant key builder (approval-policy.ts)",
  buildApprovalClassifierPrompt: "V2-P01 classifier prompt builder (approval-policy.ts)",
  buildGateCostLine: "V2-N3 gate-time cost preview line (approval-policy.ts)",
  createApprovalClassifier: "V2-P01 auto-approval classifier factory over ModelRuntime (approval-policy.ts)",
  parseApprovalClassifierVerdict: "V2-P01 classifier verdict parser (approval-policy.ts)",
  resolveRiskPolicy: "V2-P01 policy resolver with defaults (approval-policy.ts)",
  RISK_CLASSES: "V2-P01 closed risk-class enumeration (approval-policy.ts)",
  ApprovalClassifier: "V2-P01 classifier interface (approval-policy.ts, type)",
  ApprovalClassifierInput: "V2-P01 classifier input type (approval-policy.ts, type)",
  ApprovalClassifierOptions: "V2-P01 classifier options type (approval-policy.ts, type)",
  ApprovalClassifierResult: "V2-P01 classifier result type (approval-policy.ts, type)",
  ApprovalDecision: "V2-P01 approval decision record type (approval-policy.ts, type)",
  ApprovalDecisionKind: "V2-P01 approval decision kind union (approval-policy.ts, type)",
  ApprovalPolicyConfig: "V2-P01 per-risk-class policy type (approval-policy.ts, type)",
  GateCostLineInput: "V2-N3 gate cost-line input type (approval-policy.ts, type)",
  RiskClass: "V2-P01 risk class type (approval-policy.ts, type)",
  RiskPolicy: "V2-P01 risk policy type (approval-policy.ts, type)",
  createTrustedScriptsStore: "V2-N6 trusted-script allowlist factory (trusted-scripts.ts)",
  scriptBodyHash: "V2-N6 script-body hash helper (trusted-scripts.ts)",
  TRUSTED_SCRIPTS_FILENAME: "V2-N6 allowlist filename constant (trusted-scripts.ts)",
  TRUSTED_SCRIPTS_PROJECT_SUBDIR: "V2-N6 per-project allowlist subdir constant (trusted-scripts.ts)",
  TRUSTED_SCRIPTS_SCHEMA_VERSION: "V2-N6 allowlist schema version (trusted-scripts.ts)",
  TRUSTED_SCRIPTS_SUBDIR: "V2-N6 allowlist subdir constant (trusted-scripts.ts)",
  TrustedScriptRecord: "V2-N6 allowlist entry type (trusted-scripts.ts, type)",
  TrustedScriptsStore: "V2-N6 allowlist store interface (trusted-scripts.ts, type)",
  TrustedScriptsStoreOptions: "V2-N6 allowlist store options type (trusted-scripts.ts, type)",
  CheckpointOptions: "V2-P01/V2-N3 checkpoint options type incl. riskClass/details (workflow.ts, type)",
  machineValidateTest: "W2 P01 testGate machine validator (test-gate.ts)",
  validateTestGateTests: "W2 P01 testGate tests validator (test-gate.ts)",
  buildTestGateFeedback: "W2 P01 testGate rework-feedback builder (test-gate.ts)",
  buildTestGatePrompt: "W2 P01 testGate subagent prompt builder (test-gate.ts)",
  capTestGateOutput: "W2 P01 testGate output capper (test-gate.ts)",
  TEST_GATE_OUTPUT_SCHEMA: "W2 P01 testGate subagent capture schema (test-gate.ts)",
  TestGateAssert: "W2 P01 testGate assert type (test-gate.ts, type)",
  TestGateStepResult: "W2 P01 testGate step-result type (test-gate.ts, type)",
  TestGateTest: "W2 P01 testGate test type (test-gate.ts, type)",
  TestGateTool: "W2 P01 testGate tool type (test-gate.ts, type)",
  CrosscheckVerdict: "W2 P09 cross-check verdict type (model-crosscheck.ts, type)",
  ModelCrosschecker: "W2 P09 cross-checker interface (model-crosscheck.ts, type)",
  ModelCrosscheckerOptions: "W2 P09 cross-checker options type (model-crosscheck.ts, type)",
  bindRunSupervisor: "W4 P02 supervisedRun runtime-global factory (supervisor.ts)",
  buildCorrectionPrompt: "W4 P02 corrective-agent prompt builder (supervisor.ts)",
  buildSupervisorPrompt: "W4 P02 supervisor check prompt builder (supervisor.ts)",
  createSupervisorController: "W4 P02 settle-path observation controller (supervisor.ts)",
  generateSupervisedRunWorkflow: "W4 P02 supervised-run builtin generator (supervisor.ts)",
  parseSupervisorVerdict: "W4 P02 supervisor verdict parser (supervisor.ts)",
  SUPERVISED_RUN_NUMERIC_ARGS: "W4 P02 supervised-run numeric-arg spec (supervisor.ts)",
  SUPERVISOR_DEFAULT_MAX_ROUNDS: "W4 P02 supervisor default round bound (supervisor.ts)",
  SUPERVISOR_VERDICT_SCHEMA: "W4 P02 supervisor verdict schema (supervisor.ts)",
  RunSupervisorContext: "W4 P02 supervisor run context type (supervisor.ts, type)",
  SupervisedRunConfig: "W4 P02 supervised-run config type (supervisor.ts, type)",
  SupervisedRunOptions: "W4 P02 supervisedRun options type (supervisor.ts, type)",
  SupervisedRunOutcome: "W4 P02 supervisedRun outcome type (supervisor.ts, type)",
  SupervisorBudget: "W4 P02 supervisor budget surface (supervisor.ts, type)",
  SupervisorController: "W4 P02 supervisor controller type (supervisor.ts, type)",
  SupervisorObservation: "W4 P02 supervisor observation type (supervisor.ts, type)",
  SupervisorSettleEvent: "W4 P02 settle-tap event type (supervisor.ts, type)",
  SupervisorVerdict: "W4 P02 supervisor verdict type (supervisor.ts, type)",
  DEFAULT_TOKEN_BUDGET: "config constant",
  DEFAULT_MAX_TOTAL_OUTPUT_CHARS: "V2-QW3 config constant (run-level output ceiling default)",
  resolveMaxTotalOutputChars: "V2-QW3 config helper (ceiling resolution: option > env > none)",
  WORKFLOW_RUNS_DIR: "config constant",
  WORKFLOW_SAVED_DIR: "config constant",
  USER_WORKFLOW_SAVED_DIR: "config constant",
  MODEL_TIERS_FILE: "config constant",
  WORKFLOW_SETTINGS_FILE: "config constant",
  DEFAULT_KEYWORD_TRIGGER_WORD: "config constant",
  normalizeKeywordTriggerWord: "config helper",
  AGENTS_DIR: "config constant",
  DEFAULT_RETRY_BACKOFF_MS: "config constant (run retry backoff)",
  MAX_RETRY_BACKOFF_MS: "config constant (run retry backoff)",
  // ── errors / gate codes (callers switch on these) ──
  WorkflowError: "public error type",
  WorkflowErrorCode: "public error-code enum",
  isWorkflowError: "public guard",
  isAbortError: "public guard",
  isTimeoutError: "public guard",
  wrapError: "public helper",
  APPROVAL_REQUIRED: "phase gate code (phases-machinery)",
  PHASE_TRANSITION_INVALID: "phase gate code (phases-machinery)",
  SUBAGENT_SPAWN_BLOCKED: "phase gate code (phases-machinery)",
  WorkflowStateManager: "phases machinery",
  // ── agent / runtime machinery ──
  WorkflowAgent: "agent runner",
  applyToolPolicy: "agent registry surface",
  compactAgentHistory: "agent history",
  listAgentTypes: "agent registry surface",
  loadAgentRegistry: "agent registry surface",
  resolveAgentType: "agent registry surface",
  listAvailableModels: "agent registry surface",
  listAvailableModelSpecs: "agent registry surface",
  createWorktreeRunner: "worktree isolation",
  executeTask: "worktree isolation",
  implementProtocol: "worktree isolation",
  MCPProxyClient: "proxied tools",
  createProxiedTools: "proxied tools",
  MCPBridge: "host-tool gateway bridge",
  // ── provider pool (per-provider concurrency + run-sticky routing) ──
  ProviderPool: "provider pool service",
  createProviderPoolFromConfig: "provider pool factory",
  ProviderPoolConfig: "provider pool config type",
  ProviderPoolOptions: "provider pool options type",
  ProviderPoolEntry: "provider pool entry type",
  ProviderPoolSnapshot: "provider pool snapshot type",
  ProviderPoolSnapshotEntry: "provider pool snapshot entry type",
  ProviderChoice: "provider pool choice type",
  ProviderPoolEntryInput: "provider pool settings input type",
  ProviderPoolModelInput: "provider pool settings model input type",
  ProviderPoolSettingsInput: "provider pool settings input type",
  normalizeProviderPoolConfig: "provider pool config normalization",
  parseProviderPoolEnvJson: "provider pool env JSON parser",
  providerPoolFromEnv: "provider pool env override reader",
  DEFAULT_WHEN_SATURATED: "provider pool default",
  DEFAULT_SATURATION_WAIT_TIMEOUT_MS: "provider pool default",
  DEFAULT_TPM_WINDOW_MS: "provider pool default",
  DEFAULT_COOLDOWN_MS: "provider pool default",
  PROVIDER_POOL_ENV_VAR: "provider pool env var name",
  createPlannotatorBridge: "plan review bridge",

  getPlanStatus: "plan review bridge",
  submitPlan: "plan review bridge",
  waitForApproval: "plan review bridge",
  createWorkflowLogger: "logger factory",
  createRunPersistence: "persistence factory",
  createRunState: "persistence",
  generateRunId: "persistence",
  listActiveRuns: "persistence",
  loadRunState: "persistence",
  resumeRun: "persistence (resume)",
  saveCheckpoint: "persistence (checkpoint)",
  cleanupRun: "persistence",
  // settings loading / saving
  saveWorkflowSettings: "settings saving",
  // ── workflows-settings field registry (settings surface) ──
  FIELD_REGISTRY: "workflows-settings field registry",
  FIELD_GROUPS: "workflows-settings field registry",
  SettingsFormModel: "workflows-settings form state",
  fieldDisplayValue: "workflows-settings field display",
  getEnvLockedKeys: "workflows-settings env locks",
  getField: "workflows-settings field lookup",
  parseFieldInput: "workflows-settings input validation",
  SharedStore: "shared store",
  createStructuredOutputTool: "structured output",
  createWebFetchTool: "web tools",
  createWebSearchTool: "web tools",
  createWorktree: "worktree lifecycle",
  removeWorktree: "worktree lifecycle",
  // ── display / TUI ──
  createWorkflowSnapshot: "display",
  recomputeWorkflowSnapshot: "display",
  renderWorkflowLines: "display",
  renderWorkflowText: "display",
  preview: "display",
  createToolUpdateWorkflowDisplay: "display",
  createWidgetWorkflowDisplay: "display",
  deliverText: "result delivery",
  openWorkflowNavigator: "workflow UI",
  renderNavigator: "workflow UI",
  NavigatorModel: "workflow UI",
  NavigatorState: "workflow UI",
  keyToAction: "workflow UI",
  // ── effort / arming ──
  effortDirective: "effort machinery",
  isSubstantive: "effort machinery",
  buildArmedWorkflowPrompt: "keyword arming",
  buildForcedWorkflowPrompt: "keyword arming",
  endsWithTrigger: "keyword arming",
  hasTrigger: "keyword arming",
  registerWorkflowProgressCommands: "keyword arming",
  registerWorkflowTriggerCommand: "keyword arming",
  // ── gateway error constants (stable, callers compare against them) ──
  CONNECTION_CLOSED: "gateway constant",
  INTERNAL_ERROR: "gateway constant",
  INVALID_PARAMS: "gateway constant",
  INVALID_REQUEST: "gateway constant",
  METHOD_NOT_FOUND: "gateway constant",
  PARSE_ERROR: "gateway constant",
  TOOL_EXECUTION_ERROR: "gateway constant",
  TOOL_NOT_FOUND: "gateway constant",
  TOOL_TIMEOUT: "gateway constant",
  GATEWAY_NOT_RUNNING_MESSAGE: "gateway message",
  // ── usage-limit scheduler ──
  computeAutoResumeDelayMs: "usage-limit scheduler",
  parseResetHintMs: "usage-limit scheduler",
  // ── model routing / tiers ──
  classifyTask: "model routing",
  TaskClassification: "model routing",
  tierNameForTask: "model routing",
  tierNameForClassification: "model routing",
  parseModelRoutingFromMeta: "model routing",
  resolveModelForPhase: "model routing",
  canonicalModelSpec: "model specs",
  formatModelSpecWithThinking: "model specs",
  isThinkingLevel: "model specs",
  resolveModelSpecWithThinking: "model specs",
  splitModelSpecThinking: "model specs",
  THINKING_LEVELS: "model specs",
  buildDefaultTierConfig: "model tier config",
  formatTierFallbackNotice: "model tier config",
  getModelTierConfigPath: "model tier config",
  loadModelTierConfig: "model tier config",
  resolveTierModel: "model tier config",
  saveModelTierConfig: "model tier config",
  sortedTierNames: "model tier config",
  // ── phases / wayfinder ──
  generateBlueprint: "phases prewalk",
  loadBlueprint: "phases prewalk",
  saveBlueprint: "phases prewalk",
  validateBlueprint: "phases prewalk",
  assessPrompt: "wayfinder",
  beginSession: "wayfinder",
  blockTicket: "wayfinder",
  buildResearchPrompt: "wayfinder",
  createDecisionMap: "wayfinder",
  dispatchTicketResearch: "wayfinder",
  getNextAction: "wayfinder",
  getSessionTicket: "wayfinder",
  loadDecisionMap: "wayfinder",
  renderMarkdownMap: "wayfinder",
  resolveTicket: "wayfinder",
  saveDecisionMap: "wayfinder",
  unblockTicket: "wayfinder",
  // ── saved commands ──
  parseCommandArgs: "saved commands",
  registerSavedWorkflow: "saved commands",
  assertSafeSavedWorkflowName: "saved-workflow safety",
  isSafeSavedWorkflowName: "saved-workflow safety",
  // ── workflow status / locking ──
  acquireFileLock: "workflow status",
  checkFileConflict: "workflow status",
  createWorktreeWriteClaimer: "workflow status (B3 live claimer)",
  getWorkflowStatus: "workflow status",
  listRunningWorkflows: "workflow status",
  releaseFileLock: "workflow status",
  WorktreeWriteClaimer: "workflow status (B3 live claimer)",
  WorktreeWriteClaimerOptions: "workflow status (B3 live claimer)",
  // ── workflow paths ──
  WORKFLOW_HOME_RELATIVE_DIR: "workflow paths",
  WORKFLOW_PROJECTS_SUBDIR: "workflow paths",
  workflowHomeDir: "workflow paths",
  workflowProjectKey: "workflow paths",
  workflowProjectPaths: "workflow paths",
  workflowUserSavedDir: "workflow paths",
  getWorkflowProjectSettingsPath: "settings paths",
  getWorkflowSettingsPath: "settings paths",
  // ── workflow tool ──
  backgroundStartedText: "workflow tool",
  formatCompletedResultText: "workflow tool (M18 completed-run text)",
  // ── workflow damage-control toolset (extension lazy-loads it; unit + e2e suites) ──
  createWorkflowDamageControlTool: "damage-control tool factory (extension lazy-load, e2e suite)",
  DAMAGE_CONTROL_ACTIONS: "damage-control verb matrix",
  DAMAGE_CONTROL_READONLY_ACTIONS: "damage-control readonly verb matrix",
  allowedDamageControlActions: "damage-control verb matrix helper",
  classifyRecoveryAction: "damage-control recovery classification",
  collectCleanCandidates: "damage-control clean candidates",
  formatDamageControlText: "damage-control text rendering",
  normalizeDamageControlInput: "damage-control input validation",
  reconcileAgentAfterKill: "damage-control kill reconcile",
  summarizeAgents: "damage-control agent summary",
  summarizeRunDeep: "damage-control deep run summary",
  AgentSummary: "damage-control type",
  CleanCandidate: "damage-control type",
  CleanReport: "damage-control type",
  DamageControlAction: "damage-control type",
  DamageControlCapabilities: "damage-control type",
  DamageControlInput: "damage-control type",
  DeepRunSummary: "damage-control type",
  KillAgentResult: "damage-control type",
  RecoveryClassification: "damage-control type",
  RecoveryOutcome: "damage-control type",
  WorkflowDamageControlToolOptions: "damage-control tool type",
  // ── lazy peer dependencies (H4) ──
  MissingPeerError: "lazy peer diagnostics",
  isMissingPeerError: "lazy peer diagnostics",
  PEER_DEPENDENCIES: "lazy peer diagnostics",
  lazyPeerImport: "lazy peer diagnostics",
  probePeerAvailability: "lazy peer diagnostics",
  // ── capability contract ──
  defineWorkflowCapabilityContract: "capability contract",
  WORKFLOW_CAPABILITY_CONTRACT: "capability contract",
  WORKFLOW_CAPABILITY_DEFINITION: "capability contract",
  CapabilityClassification: "capability contract",
  CapabilityOrigin: "capability contract",
  CapabilitySupport: "capability contract",
  DiagnosticSeverity: "capability contract",
  DiscoveryPlacement: "capability contract",
  WorkflowCapabilityContractError: "capability contract",
  // ── public types (renames break consumer type imports) ──
  WorkflowSettings: "settings type",
  WorkflowSettingsOptions: "settings type",
  WorkflowSettingsStore: "settings type",
  FormResult: "workflows-settings form type",
  SettingsScope: "workflows-settings scope type",
  WorkflowSettingsField: "workflows-settings field type",
  WorkflowSettingsFieldGroup: "workflows-settings field type",
  WorkflowSettingsFieldType: "workflows-settings field type",
  WorkflowToolInput: "workflow tool type",
  WorkflowToolOptions: "workflow tool type",
  WorkflowControlInput: "workflow control tool type",
  WorkflowControlRunDetails: "workflow control tool type",
  WorkflowControlToolOptions: "workflow control tool type",
  WorkflowManagerOptions: "workflow manager type",
  ManagedRun: "workflow manager type",
  WorkflowRunOptions: "workflow run type",
  WorkflowRunResult: "workflow run type",
  WorkflowMeta: "workflow meta type",
  WorkflowMetaPhase: "workflow meta phase type",
  AgentOptions: "agent options type",
  AgentRunOptions: "agent run options type",
  AgentRunResult: "agent run result type",
  WorkflowAgentOptions: "agent options type",
  RunResult: "worktree runner type",
  WorktreeRunner: "worktree runner type",
  WorktreeRunnerConfig: "worktree runner type",
  WorktreeTask: "worktree runner type",
  Worktree: "worktree type",
  PlannotatorBridge: "plannotator type",
  PlannotatorConfig: "plannotator type",
  ReviewPlan: "plannotator type",
  PersistedRunState: "persistence type",
  RunCheckpoint: "persistence type",
  RunCheckpointState: "persistence type",
  RunLeaseInfo: "persistence type",
  RunPersistence: "persistence type",
  RunStatus: "persistence type",
  SavedWorkflow: "saved workflow type",
  WorkflowStorage: "saved workflow type",
  WorkflowStatus: "status type",
  FileLock: "status type",
  JournalEntry: "journal type",
  PhaseOptions: "phase type",
  PhaseStateIntegration: "phase type",
  PhaseState: "phase type",
  SharedRuntime: "runtime type",
  CheckpointGate: "checkpoint type",
  WorkflowDisplay: "display type",
  WorkflowDisplayOptions: "display type",
  WorkflowSnapshot: "display type",
  WorkflowAgentSnapshot: "display type",
  WorkflowAgentStatus: "display type",
  TaskPanelOptions: "task panel type",
  AutoResumeDelayParams: "usage-limit scheduler type",
  SchedulableWorkflowManager: "usage-limit scheduler type",
  TimerHandle: "usage-limit scheduler type",
  UsageLimitSchedulerOptions: "usage-limit scheduler type",
  EffortLevel: "effort type",
  EffortState: "effort type",
  ArmReason: "arming type",
  InstallWorkflowKeywordArmingOptions: "arming type",
  WorkflowModeState: "arming type",
  NavAction: "UI type",
  ViewKind: "UI type",
  WorkflowLogger: "logger type",
  WorkflowLoggerOptions: "logger type",
  StructuredOutputCapture: "structured output type",
  StructuredOutputToolOptions: "structured output type",
  HostToolsBundle: "gateway type",
  SessionManagerLike: "gateway type",
  SessionManagerProvider: "gateway type",
  WorkflowGatewayCommandOptions: "gateway type",
  MCPBridgeOptions: "gateway type",
  MCPProxyClientOptions: "gateway type",
  ProxiedToolDef: "gateway type",
  ToolCallResult: "gateway type",
  ToolExecutor: "gateway type",
  ModelRoute: "model routing type",
  ModelRoutingConfig: "model routing type",
  ModelThinkingLevel: "model spec type",
  ResolvedModelSpec: "model spec type",
  ModelTierConfig: "model tier type",
  RankableModel: "model tier type",
  BlueprintStep: "prewalk type",
  ExecutionBlueprint: "prewalk type",
  ClaimSource: "wayfinder type",
  CreateDecisionMapOptions: "wayfinder type",
  DecisionMap: "wayfinder type",
  DecisionTicket: "wayfinder type",
  FogAssessment: "wayfinder type",
  FrontierMappedTicket: "wayfinder type",
  FrontierMapper: "wayfinder type",
  FrontierMapping: "wayfinder type",
  ResearchDispatch: "wayfinder type",
  StatableQuestion: "wayfinder type",
  TicketClaim: "wayfinder type",
  TicketStatus: "wayfinder type",
  TicketType: "wayfinder type",
  WayfinderRuntime: "wayfinder type",
  WorkflowProjectPaths: "paths type",
  AgentDefinition: "agent registry type",
  AgentRegistry: "agent registry type",
  AgentHistoryEntry: "agent history type",
  AgentHistoryKind: "agent history type",
  AgentHistoryRole: "agent history type",
  AdversarialReviewConfig: "builtin config type",
  DeepResearchConfig: "builtin config type",
  CodeReviewAngle: "builtin code-review angle type",
  PlanThenExecuteConfig: "builtin plan-then-execute config type",
  PlanStep: "builtin plan-then-execute step type",
  StepsOrderingOutcome: "builtin plan-then-execute ordering type",
  SpecArtifact: "builtin spec-generation artifact type",
  SpecGenerationConfig: "builtin spec-generation config type",
  SpecGenerationFormat: "builtin spec-generation format type",
  SpecRequirement: "builtin spec-generation requirement type",
  AlignmentEvidence: "capability contract type",
  CapabilityDescriptor: "capability contract type",
  CapabilityDiagnostic: "capability contract type",
  DynamicReferenceDescriptor: "capability contract type",
  OptionDescriptor: "capability contract type",
  OptionShape: "capability contract type",
  PresentAtVersion: "capability contract type",
  RuntimeBindingAssembly: "capability contract type",
  StaticCapabilityFact: "capability contract type",
  WorkflowCapabilityContract: "capability contract type",
  WorkflowCapabilityDefinition: "capability contract type",
  WorkflowRuntimeImplementations: "capability contract type",
  // ── V2-P05 multi-model panel builtin (multi-model-panel.ts) ──
  generateMultiModelPanelWorkflow: "V2-P05 panel builtin generator script",
  normalizePanelModelSpecs: "V2-P05 distinct-membership normalizer (TS reference + parity test)",
  resolvePanelModelSpecs: "V2-P05 host-side panel resolution over a ModelRuntime catalog",
  basePanelModelSpec: "V2-P05 thinking-suffix-stripping distinctness helper",
  panelMode: "V2-P05 mode resolution (compare/act)",
  panelModelSpecsSource: "V2-P05 vm-embeddable distinctness normalizer source",
  PANEL_MIN_MODELS_COMPARE: "V2-P05 compare-mode panel lower bound",
  PANEL_MAX_MODELS_COMPARE: "V2-P05 compare-mode panel cap (N 2-8)",
  PANEL_MIN_MODELS_ACT: "V2-P05 act-mode reference-model lower bound",
  PANEL_MAX_MODELS_ACT: "V2-P05 act-mode reference-model cap (1-4)",
  MultiModelPanelConfig: "V2-P05 panel config shape (type)",
  PanelMode: "V2-P05 panel mode union (type)",
  // ── V2-P06 review→remediation loop (remediation.ts) ──
  injectRemediationLoop: "V2-P06 remediation-loop script transform",
  normalizeFindings: "V2-P06 finding-schema normalizer (TS reference + parity test)",
  canTransitionFinding: "V2-P06 machine-verifiable lifecycle transition predicate",
  findingContentId: "V2-P06 content-derived finding id",
  remediationNormalizersSource: "V2-P06 vm-embeddable lifecycle normalizers source",
  FINDING_LIFECYCLE_STATUSES: "V2-P06 closed lifecycle vocabulary",
  FINDING_TRANSITIONS: "V2-P06 machine-verifiable transition table",
  DEFAULT_REMEDIATION_ROUNDS: "V2-P06 default bounded fix→verify rounds",
  MAX_REMEDIATION_ROUNDS: "V2-P06 remediation rounds cap",
  FindingLifecycleRecord: "V2-P06 durable lifecycle record shape (type)",
  FindingLifecycleStatus: "V2-P06 lifecycle status union (type)",
  RemediationInjection: "V2-P06 remediation transform input (type)",
  ReviewFinding: "V2-P06 review finding shape (type)",
  // ── V2-N2 conformance-trend ledger (spec-conformance.ts fingerprint seam) ──
  normalizeWorkspaceFingerprint: "V2-N2 workspace-fingerprint capture normalizer (TS reference + parity test)",
  workspaceFingerprintKey: "V2-N2 fingerprint content-derived key",
  workspaceFingerprintSource: "V2-N2 vm-embeddable fingerprint normalizer source",
  WorkspaceFingerprintCapture: "V2-N2 fingerprint capture shape (type)",
};

const contractNames = new Set(Object.keys(ENTRY_CONTRACT));

/** Resolve the real export names of src/index.ts via the TypeScript checker. */
function resolveExportedNames(): Set<string> {
  const options: ts.CompilerOptions = {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.NodeNext,
    moduleResolution: ts.ModuleResolutionKind.NodeNext,
    strict: true,
    skipLibCheck: true,
    esModuleInterop: true,
    forceConsistentCasingInFileNames: true,
    noEmit: true,
  };
  const program = ts.createProgram([ENTRY_FILE], options);
  const checker = program.getTypeChecker();
  const sourceFile = program.getSourceFile(ENTRY_FILE);
  if (!sourceFile) {
    throw new Error(`Entry file not found: ${ENTRY_FILE}`);
  }
  const moduleSymbol = checker.getSymbolAtLocation(sourceFile);
  if (!moduleSymbol) {
    throw new Error(`Could not resolve the module symbol for ${ENTRY_FILE}`);
  }
  const names = new Set<string>();
  for (const exported of checker.getExportsOfModule(moduleSymbol)) {
    names.add(exported.name);
  }
  return names;
}

function main(): void {
  const exported = resolveExportedNames();

  const missing = [...contractNames].filter((name) => !exported.has(name)).sort();
  const undocumented = [...exported].filter((name) => !contractNames.has(name)).sort();

  if (missing.length > 0) {
    console.error(`✗ ENTRY CONTRACT BROKEN — ${missing.length} documented export(s) missing from src/index.ts:`);
    for (const name of missing) {
      console.error(`  - ${name} (${ENTRY_CONTRACT[name]})`);
    }
    console.error(
      "\nRe-export the name from src/index.ts (or, if the removal is intentional, remove it from ENTRY_CONTRACT in scripts/check-entry-contract.ts).",
    );
    process.exitCode = 1;
  } else {
    console.log(`✔ entry contract OK — all ${contractNames.size} documented exports resolve from src/index.ts.`);
  }

  if (undocumented.length > 0) {
    console.warn(`\n⚠ ${undocumented.length} export(s) not in the entry contract (gate still passes):`);
    for (const name of undocumented) {
      console.warn(`  - ${name}`);
    }
    console.warn(
      "\nAdd new public exports to ENTRY_CONTRACT in scripts/check-entry-contract.ts to keep the contract current.",
    );
  }
}

main();
